# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-01 09:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0003_auto_20160701_0917'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appuser',
            name='owner',
        ),
    ]
