# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-05 19:18
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('quickstart', '0007_auto_20160705_1745'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appuser',
            name='owner',
        ),
        migrations.AddField(
            model_name='appuser',
            name='user',
            field=models.OneToOneField(default=12, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
