# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-07 16:17
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('quickstart', '0011_remove_appuser_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='appuser',
            name='owner',
            field=models.ForeignKey(default='Name', on_delete=django.db.models.deletion.CASCADE, related_name='app_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
